blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^blogs/$', views.BlogListView.as_view(), name='blogs'),
    url(r'^blogger/(?P<pk>\d+)$', views.BlogListbyAuthorView.as_view(), name='blogs-by-author'),
    url(r'^blog/(?P<pk>\d+)$', views.BlogDetailView.as_view(), name='blog-detail'),
    url(r'^bloggers/$', views.BloggerListView.as_view(), name='bloggers'),
    url(r'^blog/(?P<pk>\d+)/comment/$', views.BlogCommentCreate.as_view(), name='blog_comment'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^blog/(?P<pk>\d+)/edit/$', views.blog_edit, name='blog_edit'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),

]

django_diy_blog/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

# Use include() to add URLS from the blog application
from django.conf.urls import include

urlpatterns += [
    url(r'^blog/', include('blog.urls')),
]

# Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView

urlpatterns += [
    url(r'^$', RedirectView.as_view(url='/blog/', permanent=True)),
]

# Add Django site authentication URLs (for login, logout, password management)
urlpatterns += [
    url('^accounts/', include('django.contrib.auth.urls')),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from datetime import date

from django.contrib.auth.models import User  # Blog author or commenter
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse  # Used to generate URLs by reversing the URL patterns


# Create your models here.


class BlogAuthor(models.Model):
    """
    Model representing a blogger.
    """
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='profile')
    # bio = models.ForeignKey(User, on_delete=models.SET_NULL, null=True,related_name='profile'))
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True, default=date.today)
    email_confirmed = models.BooleanField(default=False)

    def get_absolute_url(self):
        """
        Returns the url to access a particular blog-author instance.
        """
        return reverse('blogs-by-author', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        if self.user is None:
            return 'User doesnt Exist !'
        else:
            return self.user.username


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        BlogAuthor.objects.create(user=instance)
    instance.profile.add()


class Blog(models.Model):
    """
    Model representing a blog post.
    """
    name = models.CharField(max_length=200)
    author = models.ForeignKey(BlogAuthor, on_delete=models.SET_NULL, null=True)
    category = models.CharField(max_length=50, default="Not Defined")
    # author = models.ForeignKey(User)
    # Foreign Key used because Blog can only have one author/User, but bloggsers can have multiple blog posts.
    description = models.TextField(help_text="Enter you blog text here.", )
    post_date = models.DateField(default=date.today)
    othercontributors = models.ManyToManyField(BlogAuthor, related_name='+', )

    def __str__(self):
        return self.othercontributors

    class Meta:
        ordering = ["-post_date"]

    def get_absolute_url(self):
        """
        Returns the url to access a particular blog instance.
        """
        return reverse('blog-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.name


class BlogComment(models.Model):
    """
    Model representing a comment against a blog post.
    """
    description = models.TextField(max_length=1000, help_text="Enter comment about blog here.")
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    # Foreign Key used because BlogComment can only have one author/User, but users can have multiple comments
    post_date = models.DateTimeField(auto_now_add=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    class Meta:
        ordering = ["post_date"]

    def __str__(self):
        """
        String for representing the Model object.
        """
        len_title = 75
        if len(self.description) > len_title:
            titlestring = self.description[:len_title] + '...'
        else:
            titlestring = self.description
        return titlestring

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Blog


class inputform(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': '5', 'cols': '10', 'class': 'form-control'}),
                                  required=True, help_text="fill your story")
    name = forms.CharField(max_length=60, required=True)

    class Meta:
        model = Blog
        fields = ('name', 'description', 'category')


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    # bio = forms.CharField(max_length=30, required=False, help_text='Optional.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)


class editform(forms.Form):
    Edit = forms.CharField(widget=forms.Textarea(attrs={'rows': '5', 'cols': '10', 'class': 'form-control'}),
                           max_length=1000, required=True)

blog/views.py
from django.contrib.auth import login
from django.contrib.auth.models import User  # Blog author or commenter
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import render, redirect
# Create your views here.
from django.template.loader import render_to_string
from django.utils import timezone
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import generic

from blog.tokens import account_activation_token
from .forms import inputform, SignUpForm, editform
from .models import Blog, BlogAuthor, BlogComment


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate Your MySite Account'
            message = render_to_string('account.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(subject, message, to=[to_email])
            email.send()
            # user.email_user(subject, message)
            return redirect('account_activation_sent')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})


def account_activation_sent(request):
    return render(request, 'account_sent.html')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return render(request, 'account_invalid.html')


def post_new(request):
    if request.method == "POST":
        form = inputform(data=request.POST)

        if form.is_valid():

            blog = form.save(commit=False)
            length = len((blog.description.split()))
            if length < 10:
                # form = inputform()
                # blog.author = request.user
                my_p = BlogAuthor.objects.get(user=request.user)
                blog.author = my_p
                blog.post_date = timezone.now()
                blog.save()
                return redirect('blog-detail', pk=blog.pk)

    else:
        form = inputform()
    return render(request, 'blog/post_edit.html', {'form': form})


def blog_edit(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    if request.method == "POST":
        form = editform(request.POST)
        if form.is_valid():
            # blog = form.save(commit=False)
            # blog.author = request.user
            # blog.podt_date = timezone.now()
            currentblogauthor = BlogAuthor.objects.get(user=request.user)
            if (currentblogauthor not in blog.othercontributors.all()) and (currentblogauthor != blog.author):
                contenttobeadded = form.cleaned_data['Edit']
                blog.description += " " + contenttobeadded
                blog.save()

                if (currentblogauthor != blog.author):
                    blog.othercontributors.add(currentblogauthor)
                return redirect('blog-detail', pk=blog.pk)
            else:
                return HttpResponse("you can't update further")

    else:
        form = editform()
    context = {
        'blog': blog,
        'form': form
    }
    return render(request, 'blog/editcontribute.html', context)


def index(request):
    """
    View function for home page of site.
    """

    # Render the HTML template index.html
    blog_list = Blog.objects.all()
    return render(
        request,
        'index.html', {'blog_list': blog_list}
    )


class BlogListView(generic.ListView):
    """
    Generic class-based view for a list of all blogs.
    """
    model = Blog
    paginate_by = 5


from django.shortcuts import get_object_or_404


class BlogListbyAuthorView(generic.ListView):
    """
    Generic class-based view for a list of blogs posted by a particular BlogAuthor.
    """
    model = Blog
    paginate_by = 5
    template_name = 'blog/blog_list_by_author.html'

    def get_queryset(self):
        """
        Return list of Blog objects created by BlogAuthor (author id specified in URL)
        """
        id = self.kwargs['pk']
        target_author = get_object_or_404(BlogAuthor, pk=id)
        return Blog.objects.filter(author=target_author)

    def get_context_data(self, **kwargs):
        """
        Add BlogAuthor to context so they can be displayed in the template
        """
        # Call the base implementation first to get a context
        context = super(BlogListbyAuthorView, self).get_context_data(**kwargs)
        # Get the blogger object from the "pk" URL parameter and add it to the context
        context['blogger'] = get_object_or_404(BlogAuthor, pk=self.kwargs['pk'])
        return context


class BlogDetailView(generic.DetailView):
    """
    Generic class-based detail view for a blog.
    """
    model = Blog


class BloggerListView(generic.ListView):
    """
    Generic class-based view for a list of bloggers.
    """
    model = BlogAuthor
    paginate_by = 5


from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.urls import reverse


class BlogCommentCreate(LoginRequiredMixin, CreateView):
    """
    Form for adding a blog comment. Requires login.
    """
    model = BlogComment
    fields = ['description', ]

    def get_context_data(self, **kwargs):
        """
        Add associated blog to form template so can display its title in HTML.
        """
        # Call the base implementation first to get a context
        context = super(BlogCommentCreate, self).get_context_data(**kwargs)
        # Get the blog from id and add it to the context
        context['blog'] = get_object_or_404(Blog, pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        """
        Add author and associated blog to form data before setting it as valid (so it is saved to model)
        """
        # Add logged-in user as author of comment
        form.instance.author = self.request.user
        # Associate comment with blog based on passed id
        form.instance.blog = get_object_or_404(Blog, pk=self.kwargs['pk'])
        # Call super-class form validation behaviour
        return super(BlogCommentCreate, self).form_valid(form)

    def get_success_url(self):
        """
        After posting comment return to associated blog.
        """
        return reverse('blog-detail', kwargs={'pk': self.kwargs['pk'], })

templates/blog/base1.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>

    <!-- {% block title %}<title>welcome</title>{% endblock %} -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Custom fonts for this template -->


    <!-- Add additional CSS in static file -->


    <link href="css/clean-blog.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
          integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
          rel='stylesheet' type='text/css'>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Home</a>
        <a class="navbar-brand" href="{% url 'blogs' %}">All Blogs</a>
        <a class="navbar-brand" href="{% url 'bloggers' %}">All Bloggers</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
            Menu
            <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        {{ user.get_username }}
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}?next={{ self.path }}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}?next={{ self.path }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'signup' %}?next={{ self.path }}">Sign Up</a>
                    </li>
                {% endif %}
                <!-- <li class="nav-item">
                  <a class="nav-link" href="post.html">Sample Post</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="contact.html">Contact</a>
                </li> -->
            </ul>
        </div>
    </div>
</nav>

<!-- Page Header -->

{% block content %}
{% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/popper/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- Custom scripts for this template -->
<script src="{% static 'js/clean-blog.min.js' %}"></script>
</body>
</html>

templates/blog/blog_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <center>
        <h1>{{ blog.name }}</h1>
        <p><strong>Post date</strong> {{ blog.post_date }}</p>
        <p><strong>Writer:</strong> <a href="{% url 'blogs-by-author' blog.author.pk %}">{{ blog.author }}</a></p>
        <p><strong>Contributor(s):</strong>
            {% for each in blog.othercontributors.all %}
                <a href="{% url 'blogs-by-author' each.pk %}"> {{ each.user }}</a>
            {% endfor %}</p>

        <p><strong>Category:</strong> {{ blog.category }}</p>
        <!-- <p><strong>Description:</strong></p> -->
        <!-- <p style="white-space:pre-wrap;">{{ blog.description }}</p> -->
        <h3 class="post-subtitle">
            {{ blog.description }}
        </h3>
        <div style="margin-left:20px;margin-top:20px">

            {% if user.is_authenticated %}
                <b> Contribute to the story</b>
                <a class="btn btn-default" href="{% url 'blog_edit' pk=blog.pk %}"><span
                        class="glyphicon glyphicon-pencil"></span></a>
                <br><br>
            {% else %}
                <p><a href="{% url 'login' %}?next={{ self.path }}">Login</a> to edit </p>
            {% endif %}

            <h4>Comments</h4>

            {% for comment in blog.blogcomment_set.all %}
                <hr>
                <p>{{ comment.author }} ({{ comment.post_date }}) - {{ comment.description }}</p>
            {% endfor %}
            <hr>
            {% if user.is_authenticated %}



                <a href="{% url 'blog_comment' blog.id %}">Add a new comment</a></p>
            {% else %}
                <p><a href="{% url 'login' %}?next={{ self.path }}">Login</a> to add a new comment</p>



            {% endif %}


        </div>
    </center>
{% endblock %}

templates/blog/blog_list.html
{% extends "base_generic.html" %}

{% block content %}
    <center>
        <h1>All blogs</h1>

        {% if blog_list %}
            <div class="container">
            <div class="row">
            <div class="col-lg-12 col-md-10 mx-auto">
            {% for blog in blog_list %}
                <hr>
                <div class="post-preview">
                    <a href="{{ blog.get_absolute_url }}">
                        <h2 class="post-title">
                            {{ blog.name }}
                        </h2>
                        <h3 class="post-subtitle">
                            {{ blog.description }}
                        </h3>
                    </a>
                    <p class="post-meta">Posted by
                        <a href="{% url 'blogs-by-author' blog.author.pk %}">{{ blog.author }}</a>
                        on {{ blog.post_date }}</p>
                </div>
            {% endfor %}

        {% else %}
            <p>There are no blogs.</p>
        {% endif %}
    </center>
{% endblock %}

templates/blog/blog_list_by_author.html
{% extends "base_generic.html" %}

{% block content %}
    <center>

    <h1>Author: {{ blogger }}</h1>

    <h4 class="post_subtitle">
        Stories written:
        {{ blog_list.count }} </h4>
    {% if blog_list %}
        <h3>Stories initiated:</h3>
        <ul>

            {% for blog in blog_list %}
                <li>
                    <h3 class="post_subtitle"><a href="{{ blog.get_absolute_url }}">{{ blog.name }}</a>
                        ({{ blog.post_date }})</a></h3>
                </li>
            {% endfor %}

        </ul>

    {% else %}
        <h3 class="post_subtitle"><p>This author hasn't posted anything yet.</p></h3>
    {% endif %}
{% endblock %}

templates/blog/blogauthor_list.html
{% extends "base_generic.html" %}

{% block content %}
    <center><b>
        <h1>All writers</h1>
        <h3 class="post-subtitle">

            {% if blogauthor_list %}
                <ul style="list-style-type: none" ;>

                    {% for author in blogauthor_list %}
                        <li>
                            <a href="{% url 'blogs-by-author' author.pk %}">{{ author }}</a></li>

                    {% endfor %}
                </ul>

            {% else %}
                <p>There are no writers yet.</p>

                </h3>
            {% endif %}
    </b>
    </center>
{% endblock %}

templates/blog/blogcomment_form.html
{% extends "base_generic.html" %}

{% block content %}
    <p>Post your comment for: <a href="{% url 'blog-detail' blog.pk %}">{{ blog.name }}</a></p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit"/>

    </form>
{% endblock %}

templates/blog/editcontribute.html
{% extends "base_generic.html" %}

{% block content %}
    <center>

        <h1 style="font-family:serif;"><b> Your contribution is welcome!<br>Update this blog</b></h1>
        <h1><b>{{ blog.name }}</b></h1>
        <h3><p><strong>Current Description:</strong></p></h3>

        <h4><p style="white-space:pre-wrap; font-family:courier;">{{ blog.description }}</p></h4>

        <form method="post">
            {% csrf_token %}
            {{ form }}
            <br>
            <input type="submit" value="Done editing"
                   style="font-size: 16px;color:black;background-color:#e7e7e7;border:2px solid #336600;padding: 12px 28px;border-radius: 8px;"/>
        </form>
    </center>
{% endblock %}

templates/blog/index1.html
{% extends "base1.html" %}
{% load staticfiles %}
{% block content %}
    <header class="masthead" style="background-image: url('img/home-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Welcome to Extendo</h1>
                        <span class="subheading">Let your ideas be more creative!</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Man must explore, and this is exploration at its greatest
                        </h2>
                        <h3 class="post-subtitle">
                            Problems look mighty small from 150 miles up
                        </h3>
                    </a>
                    <p class="post-meta">Posted by
                        <a href="#">Start Bootstrap</a>
                        on September 24, 2017</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            I believe every human has a finite number of heartbeats. I don't intend to waste any of
                            mine.
                        </h2>
                    </a>
                    <p class="post-meta">Posted by
                        <a href="#">Start Bootstrap</a>
                        on September 18, 2017</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Science has not yet mastered prophecy
                        </h2>
                        <h3 class="post-subtitle">
                            We predict too much for the next year and yet far too little for the next ten.
                        </h3>
                    </a>
                    <p class="post-meta">Posted by
                        <a href="#">Start Bootstrap</a>
                        on August 24, 2017</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Failure is not an option
                        </h2>
                        <h3 class="post-subtitle">
                            Many say exploration is part of our destiny, but it’s actually our duty to future
                            generations.
                        </h3>
                    </a>
                    <p class="post-meta">Posted by
                        <a href="#">Start Bootstrap</a>
                        on July 8, 2017</p>
                </div>
                <hr>
                <!-- Pager -->
                <div class="clearfix">
                    <a class="btn btn-secondary float-right" href="#">Older Posts &rarr;</a>
                </div>
            </div>
        </div>
    </div>


    <hr>
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
              </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
              </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
              </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2017</p>
                </div>
            </div>
        </div>
    </footer>

{% endblock %}

templates/blog/post_edit.html
{% extends "base_generic.html" %}

{% block content %}
    <center>
        <p>
        <h1>Here you go...</h1></p>
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Save</button>
        </form>
    </center>
{% endblock %}