blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^blogs/$', views.BlogListView.as_view(), name='blogs'),
    url(r'^blogger/(?P<pk>\d+)$', views.BlogListbyAuthorView.as_view(), name='blogs-by-author'),
    url(r'^blog/(?P<pk>\d+)$', views.BlogDetailView.as_view(), name='blog-detail'),
    url(r'^bloggers/$', views.BloggerListView.as_view(), name='bloggers'),
    url(r'^blog/(?P<pk>\d+)/comment/$', views.BlogCommentCreate.as_view(), name='blog_comment'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^blog/(?P<pk>\d+)/edit/$', views.blog_edit, name='blog_edit'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),

]

django_diy_blog/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

# Use include() to add URLS from the blog application
from django.conf.urls import include

urlpatterns += [
    url(r'^blog/', include('blog.urls')),
]

# Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView

urlpatterns += [
    url(r'^$', RedirectView.as_view(url='/blog/', permanent=True)),
]

# Add Django site authentication URLs (for login, logout, password management)
urlpatterns += [
    url('^accounts/', include('django.contrib.auth.urls')),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from datetime import date

from django.contrib.auth.models import User  # Blog author or commenter
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse  # Used to generate URLs by reversing the URL patterns


# Create your models here.


class BlogAuthor(models.Model):
    """
    Model representing a blogger.
    """
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='profile')
    # bio = models.ForeignKey(User, on_delete=models.SET_NULL, null=True,related_name='profile'))
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True, default=date.today)
    email_confirmed = models.BooleanField(default=False)

    def get_absolute_url(self):
        """
        Returns the url to access a particular blog-author instance.
        """
        return reverse('blogs-by-author', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        if self.user is None:
            return 'User doesnt Exist !'
        else:
            return self.user.username


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        BlogAuthor.objects.create(user=instance)
    instance.profile.add()


class Blog(models.Model):
    """
    Model representing a blog post.
    """
    name = models.CharField(max_length=200)
    author = models.ForeignKey(BlogAuthor, on_delete=models.SET_NULL, null=True)
    category = models.CharField(max_length=50, default="Not Defined")
    # author = models.ForeignKey(User)
    # Foreign Key used because Blog can only have one author/User, but bloggsers can have multiple blog posts.
    description = models.TextField(help_text="Enter you blog text here.", )
    post_date = models.DateField(default=date.today)
    othercontributors = models.ManyToManyField(BlogAuthor, related_name='+', )

    def __str__(self):
        return self.othercontributors

    class Meta:
        ordering = ["-post_date"]

    def get_absolute_url(self):
        """
        Returns the url to access a particular blog instance.
        """
        return reverse('blog-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.name


class BlogComment(models.Model):
    """
    Model representing a comment against a blog post.
    """
    description = models.TextField(max_length=1000, help_text="Enter comment about blog here.")
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    # Foreign Key used because BlogComment can only have one author/User, but users can have multiple comments
    post_date = models.DateTimeField(auto_now_add=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    class Meta:
        ordering = ["post_date"]

    def __str__(self):
        """
        String for representing the Model object.
        """
        len_title = 75
        if len(self.description) > len_title:
            titlestring = self.description[:len_title] + '...'
        else:
            titlestring = self.description
        return titlestring

templates/account.html
{% autoescape off %}
    Hi {{ user.username }},

    Please click on the link below to confirm your registration:

    http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

templates/account_invalid.html
{% extends 'base_generic.html' %}

{% block content %}
    <p>The confirmation link was invalid, possibly because it has already been used.</p>
{% endblock %}

templates/account_sent.html
{% extends 'base_generic.html' %}

{% block content %}
    <h3 class="post-subtitle"><p>Please confirm your email address to complete the registration. </p></h3>
{% endblock %}

templates/base_generic.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<script>
    $(function () {
        $('body').show();
    });
</script>
<head>

    <!-- {% block title %}<title>welcome</title>{% endblock %} -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Custom fonts for this template -->


    <!-- Add additional CSS in static file -->


    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
          rel='stylesheet' type='text/css'>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/popper/popper.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<!-- <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">

      </div>
      <ul class="nav navbar-nav">
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="{% url 'blogs' %}">All Blogs</a></li>
        <li><a href="{% url 'bloggers' %}">All Bloggers</a></li>

      </ul>
    </div>
  </nav> -->
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div id="navb" class="navbar-header">
            <a class="navbar-brand" href="{% url 'index' %}">Extendo</a>
        </div>
        <ul id="list" class="nav navbar-nav navbar-right">
            <li class="all blogs"><a href="{% url 'blogs' %}">All Posts</a></li>
            <li class="all bloggers"><a href="{% url 'bloggers' %}">All Writers</a></li>
            {% if user.is_authenticated %}
                <li class="username"><a href="{% url 'index' %}?next={{ self.path }}">{{ user.get_username }}</a></li>
                <li class="logout"><a class="logout-link" href="{% url 'logout' %}?next={{ self.path }}">Logout</a></li>
            {% else %}
                <li class="login"><a class="login-link" href="{% url 'login' %}?next={{ self.path }}">Login</a></li>
                <li class="signup"><a class="signup-link" href="{% url 'signup' %}?next={{ self.path }}">Sign Up</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<header class="masthead"
        style="background-image: url( https://static-ssl.businessinsider.com/image/579280c8dd0895cb0c8b4b1d-2400/apple-iphone-smartphone-desk.jpg )">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>Welcome to Extendo</h1>
                    <span class="subheading">Let your ideas be more creative!</span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index' %}">Home</a>
      <a class="navbar-brand" href="{% url 'blogs' %}">All Blogs</a>
      <a class="navbar-brand" href="{% url 'bloggers' %}">All Bloggers</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fa fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
           <li class="nav-item">
          {{ user.get_username }}
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout'%}?next={{self.path}}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login'%}?next={{self.path}}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'signup'%}?next={{self.path}}">Sign Up</a>
          </li>
          {% endif %}

        </ul>
      </div>
    </div>
  </nav> -->

<!-- Page Header -->

{% block content %}

{% endblock %}
<p align="right">
    <small class="credit">Made with ♥ by <b>Crusaders</b></small></p>


</body>
</html>

templates/home.html
{% extends 'base_generic.html' %}

{% block content %}
    <h2>Welcome, {{ user.get_full_name }} <small>{{ user.username }}</small>!</h2>
    <p>Thanks for confirming your email address!</p>
{% endblock %}

templates/index.html
{% extends "base_generic.html" %}
{% load staticfiles %}
{% block content %}
    <center>


        <!-- Main Content -->
        {% if blog_list %}
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-10 mx-auto">
                        <div class="post-preview"><h2 class="post-title">Add a new post</div>
                        <br>
                    </div>
                </div>
            </div>
            </div>
        {% endif %}
        <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span><br><br></a>
        <!-- <hr>
        <div class="post-preview">
          <a href="post.html">
            <h2 class="post-title">
              I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.
            </h2>
          </a>
          <p class="post-meta">Posted by
            <a href="#">Start Bootstrap</a>
            on September 18, 2017</p>
        </div>
        <hr>
        <div class="post-preview">
          <a href="post.html">
            <h2 class="post-title">
              Science has not yet mastered prophecy
            </h2>
            <h3 class="post-subtitle">
              We predict too much for the next year and yet far too little for the next ten.
            </h3>
          </a>
          <p class="post-meta">Posted by
            <a href="#">Start Bootstrap</a>
            on August 24, 2017</p>
        </div>
        <hr>
        <div class="post-preview">
          <a href="post.html">
            <h2 class="post-title">
              Failure is not an option
            </h2>
            <h3 class="post-subtitle">
              Many say exploration is part of our destiny, but it’s actually our duty to future generations.
            </h3>
          </a>
          <p class="post-meta">Posted by
            <a href="#">Start Bootstrap</a>
            on July 8, 2017</p>
        </div>
        <hr> -->
        <!-- Pager -->
        <div class="clearfix">
            <a class="btn btn-secondary float-right" href="{% url 'blogs' %}"><p>Read all blogs &rarr;</p></a>
        </div>
        </div>
        </div>
        </div>


        <hr>

    </center>
{% endblock %}

templates/signup.html
{% extends 'base_generic.html' %}

{% block content %}
    <center>
        <h2>Sign up</h2>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <p>
                    {{ field.label_tag }}<br>
                    {{ field }}
                    {% if field.help_text %}

                    {% endif %}
                    {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </p>
            {% endfor %}
            <button type="submit" style="background-color: #555555;
    color: white;background-color: white;
    color: black;
    border: 2px solid #555555;background-color: #555555; /* Green */
    border: none;
    color: white;
    padding: 16px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    -webkit-transition-duration: 0.4s; /* Safari */
    transition-duration: 0.4s;
    cursor: pointer;">Sign up
            </button>
        </form>
    </center>
{% endblock %}